[model]
name = "ensemble.ExtraTreesClassifier"

[params]
n_jobs = -1
n_estimators = 150
random_state = 42

[split]
train_size = 0.8

[paths]
models = "E:/Python/mock_data_science_project/models"
images = "E:/Python/mock_data_science_project/images"
metrics = "E:/Python/mock_data_science_project/metrics"